config/routes.rb
Rails.application.routes.draw do
  get 'assessment_seasons/index'
  get 'assessments/new'
  get 'sessions/new'
  get 'users/new'
  get 'home/index'
  get 'registration', to: 'users#new'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  resources :assessments
  resources :assessment_seasons, except: [:show]
  delete 'sessions', to: 'sessions#destroy'
  root 'home#index'
end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :assessments
  has_many :roles, through: :assessments

  before_save :make_email_downcase

  has_secure_password
  validates :firstname, presence: true, length: {minimum:2, maximum:50}
  validates :lastname, presence: true, length: {minimum:2, maximum:50}
  validates :department, presence: true, length: {minimum:4, maximum:100}
  validates :job_title, presence: true, length: {minimum:4, maximum:100}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {minimum:4, maximum:150}, format: {with: VALID_EMAIL_REGEX}

  def display_name
    "#{firstname} #{lastname}"
  end

  private

  def make_email_downcase
    self.email = email.strip.downcase
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid? && @user.password != params[:user][:password2]
      flash.now[:danger] = "Passwords do not match."
      render 'new'
    else
      if @user.save
        session[:user_id] = @user.id
        session[:expires_at] = Time.current + 30.minutes 
        flash[:success] = "Congratulations. Your registration has been successful."
        redirect_to root_path
      else
        flash.now[:danger] = "Something went wrong. Please correct the marked fields below."
        render 'new'
      end
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Account information has been updated successfully."
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

  def destroy
    if @user.destroy
      flash[:success] = "Account has been deleted."
      session[:user_id] = nil
      redirect_to root_path
    else
      flash.now[:danger] = "Unable to delete."
      redirect_to root_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:firstname, :lastname, :job_title, :department, :email, :password, :is_admin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def validated_class(input)
    if @user.errors[input].any?
      {class: "form-control is-invalid"}
    else
      {class: "form-control"}
    end
  end

end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true, class: "row g-3 m-4") do |f| %>
  <div class="col-md-6">
    <%= f.label :firstname, class: "form-label"%>
    <%= f.text_field :firstname, validated_class(:firstname) %>
  </div>
  <div class="col-md-6">
    <%= f.label :lastname, class: "form-label"%>
    <%= f.text_field :lastname, validated_class(:firstname) %>
  </div>
  <div class="col-12">
    <%= f.label :job_title, class: "form-label"%>
    <%= f.text_field :job_title, validated_class(:job_title) %>
  </div>
  <div class="col-12">
    <%= f.label :department, class: "form-label"%>
    <%= f.text_field :department, validated_class(:department) %>
  </div>
  <div class="col-md-12">
    <%= f.label :email, class: "form-label"%>
    <%= f.email_field :email, validated_class(:email) %>
  </div>
  <div class="col-md-6">
    <%= f.label :password, "Password", class: "form-label"%>
    <%= f.password_field :password, validated_class(:password) %>
  </div>
  <div class="col-md-6">
    <%= f.label :password2, "Re-enter password", class: "form-label"%>
    <%= f.password_field :password2, validated_class(:password2) %>
  </div>
  <% if logged_in? && current_user.is_admin? %>
  <div class="col-md-12 form-check form-switch mt-4">
    <%= f.check_box :is_admin, class: "form-check-input" %>
    <%= f.label :is_admin, "Is this an admin?", class: "form-check-label" %>
  </div>
  <% end %>
  <div class="col-12 mt-5">
    <%= f.submit "Submit", class: "btn btn-success btn-lg col-4" %>
    <%= link_to "Cancel", :back, class: "btn btn-danger btn-lg col-2" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-8">
    <h1 class="display-1">Edit account</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<div class="row justify-content-md-center">
  <div class="col-12">
    <h1 class="display-1">User administration</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
  <% if @users.any? %>
    <h5><%= pluralize(@users.count, "user") %> found.</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Firstname</th>
          <th scope="col">Lastname</th>
          <th scope="col" class="col-4">Email</th>
          <th scope="col">Admin?</th>
          <th scope="col" class="col-3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
        <tr>
          <th scope="row"><%= u.id %></th>
          <td><%= u.firstname %></td>
          <td><%= u.lastname %></td>
          <td><%= u.email %></td>
          <td><%= u.is_admin? %></td>
          <td>
          <%= link_to "View profile", user_path(u), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to "Edit", edit_user_path(u), class: "btn btn-outline-warning btn-sm" %>
          <%= link_to "Delete", user_path(u), method: :delete, class: "btn btn-outline-danger btn-sm" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <h5>There are no users found.</h5>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-8">
    <h1 class="display-1">Register for an account</h1>
  </div>
</div>
<div class="row justify-content-md-center">
  <div class="col-8">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-9">
    <h1 class="display-1"><strong><%= @user.display_name %></strong></h1>
    <span class="h2"><%= @user.job_title %></span>, <span class="h5"><%= @user.department %></span>
    <div class="input-group flex-nowrap mt-5 pe-5">
      <span class="input-group-text" id="addon-wrapping"><i class="bi bi-envelope-check" style="font-size: 1.5rem"></i></span>
      <input type="text" class="form-control form-control-lg me-5" placeholder="Username" aria-label="Username" aria-describedby="addon-wrapping" value=<%= @user.email %> disabled readonly>
    </div>
  </div>
  <div class="col-3">
    <div class="d-grid gap-2 col-12 mx-auto mt-5 border border-2 border-dark rounded-3 p-4">
      <%= link_to "Edit this user", edit_user_path(@user), class: "btn btn-outline-warning btn-lg" %>
      <%= link_to "Delete this user", user_path(@user), method: :delete, class: "btn btn-outline-danger btn-lg" %>
    </div>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <% if @user.assessments.any? %>
    <h5><%= pluralize(@user.assessments.count, "submission") %> found.</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Season</th>
          <th scope="col">Role</th>
          <th scope="col">Assessor</th>
          <th scope="col" class="col-2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @user.assessments.each do |a| %>
        <tr>
          <th scope="row"><%= a.assessment_season.name %></th>
          <td><%= a.role.name %></td>
          <td><%= a.assessor_email %></td>
          <td>
          <%= link_to "View", assessment_path(a), class: "btn btn-outline-primary btn-sm" %>
          <%= link_to "Edit", edit_assessment_path(a), class: "btn btn-outline-warning btn-sm" %>
          <%= link_to "Delete", assessment_path(a), method: :delete, class: "btn btn-outline-danger btn-sm" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <h5>There are no submissions found.</h5>
    <% end %>
  </div>
</div>