config/routes.rb
Rails.application.routes.draw do
  get 'assessment_seasons/index'
  get 'assessments/new'
  get 'sessions/new'
  get 'users/new'
  get 'home/index'
  get 'registration', to: 'users#new'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  resources :assessments
  resources :assessment_seasons, except: [:show]
  delete 'sessions', to: 'sessions#destroy'
  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @roles = Role.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if logged_in? %>
  <div class="row justify-content-md-center">
    <div class="col-12 text-center mt-5 mb-5">
      <h1 class="display-1">Welcome, <%= current_user.display_name %></h1>
      <% if current_season %>
        <h3>The <mark><strong><%= current_season.name %></strong></mark> DDaT Assessment window is now open.</h3>
        <% if current_user.assessments.find_by(assessment_season: current_season).nil? %>
          <button type="button" class="btn btn-primary btn-lg mt-5" data-bs-toggle="modal" data-bs-target="#roleModal">
            Start your assessment
          </button>
        <% else %>
          <h5 class="mt-5">Congratulations, looks like you have submitted your assessment the current season already. Check your profile to view your submissions. Click on your name at top the right corner.</h5>
        <% end %>
      <% else %>
      <p>DDaT Assessment window is now closed. Please try again later.</p>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row justify-content-md-center mt-5 mb-5">
    <div class="col-12 text-center">
      <h1 class="display-1">Digital, Data and Technology</h1>
      <h1>Profession Capability Assessment</h1>
    </div>
  </div>
<% end %>


<!-- Modal -->
<div class="modal fade" id="roleModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Getting started</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= form_with(url: assessments_new_path, local: true, method: :get) do |f| %>
      <div class="modal-body">
        <%= f.label :role, "Which role are you submitting this assessment for?", class: "form-label" %>
        <%= f.select(:role, @roles.collect{|role| [role.name, role.id]}, {include_blank: "-- Select one from this list --"}, required: true, class: "form-select form-select-lg mb-3") %>
        <div class="mb-3">
          <%= f.label :assessor_email_address, class: "form-label" %>
          <%= f.email_field :assessor_email_address, class: "form-control form-control-lg", required: true, placeholder: "firstname.lastname@justice.gov.uk" %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger btn-lg col-2" data-bs-dismiss="modal">Cancel</button>
        <%= f.submit "Proceed", class: "btn btn-success btn-lg col-4" %>
      </div>
      <% end %>
    </div>
  </div>
</div>