config/routes.rb
Rails.application.routes.draw do
  get 'assessment_seasons/index'
  get 'assessments/new'
  get 'sessions/new'
  get 'users/new'
  get 'home/index'
  get 'registration', to: 'users#new'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  resources :assessments
  resources :assessment_seasons, except: [:show]
  delete 'sessions', to: 'sessions#destroy'
  root 'home#index'
end

app/models/assessment_season.rb
class AssessmentSeason < ApplicationRecord
  has_many :assessments

  scope :current_season, -> { where('end_date >= ?', Date.today).where('start_date <= ?', Date.today) }
end

app/controllers/assessment_seasons_controller.rb
class AssessmentSeasonsController < ApplicationController

  before_action :set_assessment_season, only: [:edit, :update, :delete] 
  def index
    @assessment_seasons = AssessmentSeason.all
  end

  def new
    @assessment_season = AssessmentSeason.new
  end

  def create
    @assessment_season = AssessmentSeason.new(assessment_season_params)
    if @assessment_season.save 
      flash[:success] = "A new assessment season has been created."
      redirect_to assessment_seasons_path
    else
      flash.now[:danger] = "Somethign went wrong"
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @assessment_season.update(assessment_season_params)
      flash[:success] = "Updated successfully."
      redirect_to assessment_seasons_path
    else
      flash.now[:danger] = "Something went wrong."
    end
  end

  private

  def set_assessment_season
    @assessment_season = AssessmentSeason.find(params[:id])
  end

  def assessment_season_params
    params.require(:assessment_season).permit(:name, :start_date, :end_date)
  end
end

app/helpers/assessment_seasons_helper.rb
module AssessmentSeasonsHelper
end

app/views/assessment_seasons/_assessment_season.html.erb
<%= form_with(model: @assessment_season, local: true, class: "row g-3 m-4") do |f| %>
<div class="col-8">
  <%= f.label :name, class: "form-label" %>
  <%= f.text_field :name, class: "form-control form-control-lg" %>
</div>
<div class="col-6">
  <%= f.label :start_date, class: "form-label" %>
  <%= f.date_field :start_date, class: "form-control form-control-lg" %>
</div>
<div class="col-6">
  <%= f.label :end_date, class: "form-label" %>
  <%= f.date_field :end_date, class: "form-control form-control-lg" %>
</div>
<div class="row mt-5">
  <div class="col-12">
    <%= f.submit "Save", class: "btn btn-success btn-lg col-3" %>
    <%= link_to "Cancel", :back, class: "btn btn-danger btn-lg col-3" %>
  </div>
</div>
<% end %>

app/views/assessment_seasons/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-12">
    <h1 class="display-1">Update assessment season</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <%= render @assessment_season %>
  </div>
</div>

app/views/assessment_seasons/index.html.erb
<div class="row justify-content-md-center">
  <div class="col-9">
    <h1 class="display-1">Assessment seasons</h1>
  </div>
  <div class="col-3">
    <div class="d-grid gap-2 col-12 mx-auto mt-5 border border-2 border-dark rounded-3 p-4">
      <%= link_to '<i class="bi bi-calendar2-week"></i> Add a new season'.html_safe, new_assessment_season_path, class: "btn btn-success btn-lg" %>
    </div>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
  <% if @assessment_seasons.any? %>
    <h5><%= pluralize(@assessment_seasons.count, "season") %> found.</h5>
    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Start Date</th>
          <th scope="col">End Date</th>
          <th scope="col" class="col-2">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @assessment_seasons.each do |a| %>
        <tr>
          <th scope="row"><%= a.id %></th>
          <td><%= a.name %></td>
          <td><%= a.start_date.strftime("%A, %e %B %Y") %></td>
          <td><%= a.end_date.strftime("%A, %e %B %Y") %></td>
          <td>
          <%= link_to "Edit", edit_assessment_season_path(a), class: "btn btn-outline-warning btn-sm" %>
          <%= link_to "Delete", assessment_season_path(a), method: :delete, class: "btn btn-outline-danger btn-sm" %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <% else %>
      <h5>There are no seasons found.</h5>
    <% end %>
  </div>
</div>

app/views/assessment_seasons/new.html.erb
<div class="row justify-content-md-center">
  <div class="col-12">
    <h1 class="display-1">New assessment season</h1>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <%= render @assessment_season %>
  </div>
</div>