config/routes.rb
Rails.application.routes.draw do
  get 'assessment_seasons/index'
  get 'assessments/new'
  get 'sessions/new'
  get 'users/new'
  get 'home/index'
  get 'registration', to: 'users#new'
  resources :users, except: [:new]
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  resources :assessments
  resources :assessment_seasons, except: [:show]
  delete 'sessions', to: 'sessions#destroy'
  root 'home#index'
end

app/views/layouts/_message.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name %> alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container pe-4 ps-4">
    <%= link_to "DDaT Assessment", root_path, class: "navbar-brand mb-0 h1"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to '<i class="bi bi-house"></i> Home'.html_safe, root_path, nav_link_class(root_path) %>
        </li>
        <% if logged_in? && current_user.is_admin? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-gear"></i> Administration
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "Manage users", users_path, class: "dropdown-item" %></li>
              <li><%= link_to "Manage assessment seasons", assessment_seasons_path, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-badge"></i> <%= current_user.display_name %>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to "My profile", user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to "Sign out", sessions_path, class: "dropdown-item", method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item ms-4"><%= link_to "Register", registration_path, class: "btn btn-light btn-lg" %></li>
          <li class="nav-item ms-4"><%= link_to "Sign in", signin_path, class: "btn btn-light btn-lg" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DDAT Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navigation' %>
    <div class="container shadow p-4 mb-5 bg-body rounded">
      <%= render 'layouts/message' %>
      <%= yield %>
    </div>
  </body>
</html>